### ISSUE TITLE
NullPointerException can occur when Riot API has issues

### ISSUE THREAD

**Issue by Linnun** [rithms/riot-api-java#31]
java.lang.NullPointerException
        at main.java.riotapi.RiotApi.getSummonerByName(RiotApi.java:888)

This should probably be prevented by checking if the collection is null, and returning a null object rather than trying to iterate it.

**Comment by jluzonpr** [comment]
{code}
Map<String, Summoner> summoners = SummonerApi.getSummonersByName(getEndpoint(), getRegion(), getKey(), summonerName);
for(Summoner summoner: summoners.entrySet()) {
     return summoner.getValue();
}
return null;
{code}

**Comment by Linnun** [comment]
That would also throw NullPointerExceptions, if SummonerApi.getSummonersByName() returns null.

**Comment by jluzonpr** [comment]
I don't think getSummersByName should ever return a null, If it can't find anything, it should return an empty map. Going to look at the code a bit more.

**Comment by rithms** [comment]
You are talking about the getSummonerByName methods that return a Summoner rather than a Map with a single Summoner correct?

**Comment by rithms** [comment]
Also -

Do you know the specifics of when this occurs?

If the API returns any error codes, it should throw a RiotApiException.
So I'm guessing the API is returning a 200 response code, with no data?

**Comment by Linnun** [comment]
Yes, the mentioned issue was found in the method to receive a single summoner.


I know about the RiotApiException, but sometimes there are some other issues with the connection, for example:

java.net.ConnectException: Connection timed out
or
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
or
java.io.EOFException: SSL peer shut down incorrectly



I get tons of exceptions every day, and it's hard to say which exact exception leads to which exact behavior, especially since I have a pretty big backend application using this API, running billions of requests every month.

**Comment by rithms** [comment]
If adding the null checks solve the issues, I'll go ahead and add them since it wouldn't really effect anything else.

I was just wondering about what the root cause is, because it might be better to just handle these cases in the request code than adding null check to everything.

**Comment by Linnun** [comment]
True. It seems that Riot has some really major issues for the Korean region lately: https://developer.riotgames.com/status

Maybe some of the KR requests did throw some kinds of ConnectExceptions and SSLExceptions which ended up with the summoner object being null?

In Request.java you currently catch IOException (ConnectException and SSLException extend IOException) to log them, and then return null. Maybe we shouldn't return null here, but throw a new kind of RiotApiException instead? Let's call it RiotApiException.IOEXCEPTION and throw it, instead of returning null. (This idea was inspired by this pull request: https://github.com/rithms/riot-api-java/pull/26)


I'll see if I can do some more tests with this issue.

**Comment by Linnun** [comment]
I have tested this in a live environment and it turns out that those IOExceptions are much easier to handle, when the API throws a proper Exception instead of returning a random null object (which can actually break the API, as shown in the example mentioned in the original post).


I have added a pull request (https://github.com/rithms/riot-api-java/pull/32) to change this behavior, aswell as adding a new constant Season.CURRENT.
That would also mark pull request https://github.com/rithms/riot-api-java/pull/26 as obsolete. (Thanks for the idea though, dshen6!)

**Comment by rithms** [comment]
PR https://github.com/rithms/riot-api-java/pull/32 has been merged, adding a new RiotAPIException, RiotAPIException.IOEXCEPTION. 

This issue should be fixed now, without the need to add additional null checks.

Let me know if you run into any further issues.

**Comment by jluzonpr** [comment]
Even though this was closed, I still don't see how the code would result in a null object being returned from having the execute method return an Exception. I think rithms might be correct that the request did execute correctly and GSON returned a null for some reason, but if that is the case this is not fixed and might still have random nulls being returned in places where they are not supposed to appear.

**Comment by Linnun** [comment]
I added null checks to every Gson result in this Pull Request: https://github.com/rithms/riot-api-java/pull/33

If Gson returns null for whatever reason, I throw a RiotException.PARSE_FAILURE.

**Comment by rithms** [comment]
Linnun's PR https://github.com/rithms/riot-api-java/pull/33 should now handle any cases in which GSON returns a null.

I'm going to close this issue again. If you run into anymore problems, go ahead and comment here or open a new issue.
